version: '3'

services:
  api:
    image: node:16
    environment:
      - DB_DATABASE=task
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - REDIS_HOST=redis
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - redis
    command: /bin/bash -c 'npm install;  npm start'
    ports:
      - 3000:3000
  consumer:
    image: node:16
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./task-consumer:/app
    working_dir: /app
    depends_on:
      - db
      - redis
    command: /bin/bash -c 'npm install;  npm start'
    ports:
      - 3000:3000
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=task
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    expose:
      - 3306
